image: Visual Studio 2017

version: 0.46.0.{build}
configuration: Debug
platform: Any CPU

pull_requests:
  do_not_increment_build_number: true

environment:
  CIMode: true

skip_commits:
  files:
    - '**/*.md'

before_build:
  - nuget restore ./BSLib.sln

build_script:
  - msbuild ./BSLib.sln /p:Configuration=Debug /p:Platform="Any CPU" /p:TargetFrameworkVersion=v4.0 /p:CIMode=true /p:MonoCS=true /verbosity:minimal

test_script:
  - .\packages\OpenCover\OpenCover.Console.exe -register:user -target:"nunit-console-x86.exe" -targetdir:".\BSLib.Tests\bin\Debug" -targetargs:"BSLib.Tests.dll /noshadow /framework:4.0" -output:"coverage.xml" -filter:"+[*]*"

after_test:
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "coverage.xml" -X gcov
